---

- include_tasks: Debian.yml
  when: ansible_os_family == 'Debian' 


- name: Remove vagrant previous file
  file:
    chdir: "{{ dir_vagrantfile: }}"
    path: .vagrant
    state: absent

- name: vagrant up
  shell:
    cmd: vagrant up
    chdir: "{{ dir_vagrantfile: }}"

