---
- name: Include task to setup tgroups for all known nodes that use this server
  include_tasks: _setup_server_node_tgroup.yml
  loop_control:
    loop_var: prometheus_client_fqdn
  with_items: '{{ hostvars.keys() | list | unique | sort }}'
  when:
    - "'prometheus_components' in hostvars[prometheus_client_fqdn]"
    - "'prometheus_servers' in hostvars[prometheus_client_fqdn]"
    - inventory_hostname in hostvars[prometheus_client_fqdn]['prometheus_servers']
    - not ('prometheus_tgroup_use_facts' in hostvars[prometheus_client_fqdn] and hostvars[prometheus_client_fqdn].prometheus_tgroup_use_facts)
