---
haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /var/lib/haproxy
haproxy_user: haproxy
haproxy_group: haproxy

# Frontend settings.
haproxy_frontend_name: 'hafrontend'
haproxy_frontend_bind_address: '*'
haproxy_frontend_port: 443
haproxy_frontend_mode: 'tcp'

# Backend settings.
haproxy_backend_name: 'habackend'
haproxy_backend_mode: 'tcp'
haproxy_backend_balance_method: 'roundrobin'
haproxy_backend_httpchk: 'HEAD / HTTP/1.1\r\nHost:localhost'

# List of backend servers.
haproxy_backend_servers: 
 - name: vmwp1
   address: 172.16.0.101:443
 - name: vmwp2
   address: 172.16.0.102:443

# Extra global vars (see README for example usage).
haproxy_global_vars: []

# Default haproxy timeouts
haproxy_connect_timeout: 5000
haproxy_client_timeout: 50000
haproxy_server_timeout: 50000
