Vagrant.configure("2") do |config|
    (1..2).each do |i|
        config.vm.define "vm-#{i}" do |vms|
        vms.vm.box = "bento/ubuntu-22.04"
        vms.vm.hostname = "vm-#{i}"
        vms.vm.network "public_network"
        vms.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get upgrade -y
        SHELL
        vms.vm.provision "shell" do |s|
            ssh_pub_key = File.readlines("C:\\Users\\Viktor\\.ssh\\vagrant_id_rsa.pub").first.strip
            s.inline = <<-SHELL
            echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
            SHELL
        end
        vms.vm.provider "virtulabox" do |vb|
            vb.memory = 512
            vb.cpus = 1
        end
    end
end
end