Vagrant.configure("2") do |config|

    config.vm.define "vmdb" do |vmdb|
        vmdb.vm.box = "ubuntu/focal64"
        vmdb.vm.hostname = "vmdb"
        vmdb.vm.network "public_network", bridge: "eno2", ip: "172.16.0.100"
        vmdb.vm.provision "shell",
        run: "always",
        inline: <<-SHELL
        ip route add default via 172.16.0.1 dev enp0s8
        apt-get update
        apt-get upgrade -y
        SHELL
        vmdb.vm.provision "shell" do |s|
            ssh_pub_key = File.readlines("/home/ko55ur/.ssh/vagrant_id_rsa.pub").first.strip
            s.inline = <<-SHELL
            echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
            SHELL
        end
        vmdb.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
        end
    end
    config.vm.define "vmwordpress1" do |vmwp1|
        vmwp1.vm.box = "ubuntu/focal64"
        vmwp1.vm.hostname = "vmwp1"
        vmwp1.vm.network "public_network", bridge: "eno2", ip: "172.16.0.101"
        vmwp1.vm.provision "shell",
        run: "always",
        inline: <<-SHELL 
        ip route add default via 172.16.0.1 dev enp0s8
        apt-get update
        apt-get upgrade -y
        SHELL
        vmwp1.vm.provision "shell" do |s|
            ssh_pub_key = File.readlines("/home/ko55ur/.ssh/vagrant_id_rsa.pub").first.strip
            s.inline = <<-SHELL
            echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
            SHELL
        end
        vmwp1.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
        end
    end
    config.vm.define "vmwordpress2" do |vmwp2|
        vmwp2.vm.box = "ubuntu/focal64"
        vmwp2.vm.hostname = "vmwp2"
        vmwp2.vm.network "public_network", bridge: "eno2", ip: "172.16.0.102"
        vmwp2.vm.provision "shell",
        run: "always",
        inline: <<-SHELL
        ip route add default via 172.16.0.1 dev enp0s8
        apt-get update
        apt-get upgrade -y
        SHELL
        vmwp2.vm.provision "shell" do |s|
            ssh_pub_key = File.readlines("/home/ko55ur/.ssh/vagrant_id_rsa.pub").first.strip
            s.inline = <<-SHELL
            echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
            SHELL
        end
        vmwp2.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
        end
    end
    config.vm.define "vmproxy" do |vmprx|
        vmprx.vm.box = "ubuntu/focal64"
        vmprx.vm.hostname = "vmprx"
        vmprx.vm.network "public_network", bridge: "eno2", ip: "172.16.0.103"
        vmprx.vm.provision "shell",
        run: "always",
        inline: <<-SHELL
        ip route add default via 172.16.0.1 dev enp0s8
        apt-get update
        apt-get upgrade -y
        SHELL
        vmprx.vm.provision "shell" do |s|
            ssh_pub_key = File.readlines("/home/ko55ur/.ssh/vagrant_id_rsa.pub").first.strip
            s.inline = <<-SHELL
            echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
            SHELL
        end
        vmprx.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
        end
    end
    config.vm.define "vmprometheus" do |vmprtm|
        vmprtm.vm.box = "ubuntu/focal64"
        vmprtm.vm.hostname = "vmprtm"
        vmprtm.vm.network "public_network", bridge: "eno2", ip: "172.16.0.104"
        vmprtm.vm.provision "shell",
        run: "always",
        inline: <<-SHELL 
        ip route add default via 172.16.0.1 dev enp0s8
        apt-get update
        apt-get upgrade -y
        SHELL
        vmprtm.vm.provision "shell" do |s|
            ssh_pub_key = File.readlines("/home/ko55ur/.ssh/vagrant_id_rsa.pub").first.strip
            s.inline = <<-SHELL
            echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
            SHELL
        end
        vmprtm.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
        end
    end
end
