---

- hosts: vmdb
  become: true
  remote_user: vagrant
  vars_files:
    - vars/mysql-vault.yml
    - vars/wordpress.yml
  roles:
    - { role: geerlingguy.mysql, tags: [mysql] }
    - { role: geerlingguy.node_exporter, tags: [node_exporter] }

- hosts: vmwp
  remote_user: vagrant
  become: true
  vars_files:
    - vars/wordpress.yml
    - vars/wordpress_vault.yml
    - vars/mysql-vault.yml

  roles:
    - { role: geerlingguy.nginx, tags: [nginx] }
    - { role: geerlingguy.php, tags: [php] }
    - { role: wordpress, tags: [wordpress] }
    - { role: geerlingguy.node_exporter, tags: [node_exporter] }
- hosts: vmprx
  remote_user: vagrant
  become: true
  roles:
    - { role: geerlingguy.haproxy, tags: [haproxy] }
- hosts: vmprtm
  remote_user: vagrant
  become: true
  roles:
    - { role: mesaguy.prometheus, tags: [prometheus] }
