---

- hosts: vmdb
  become: true
 # become_method: sudo
 # remote_user: vagrant
  remote_user: root
  vars_files:
    - vars/mysql-vault.yml
    - vars/wordpress.yml
  roles:
    - { role: geerlingguy.mysql, tags: [mysql] }

- hosts: vmwp
  remote_user: root
  become: true
  vars_files:
    - vars/wordpress.yml
    - vars/wordpress-vault.yml

  roles:
    - { role: geerlingguy.nginx, tags: [nginx] }
    - { role: geerlingguy.php, tags: [php] }
    - { role: wordpress, tags: [wordpress] }
